<?xml version="1.0"?>

<?xml-stylesheet href="http://www.interactivebusiness.com/publish/uPortalDevBooks/uPortalDevBooks.xsl" type="text/xsl" media="explorer"?><?xml-stylesheet href="file://C:\Documents and Settings\kweiner\Desktop\uPortalDevBooks.xsl" type="text/xsl" media="explorer"?>
<?xml-stylesheet href="http://www.interactivebusiness.com/publish/uPortalDevBooks/uPortalDevBooks.xsl" type="text/xsl" media="explorer"?><?xml-stylesheet href="file://C:\Documents and Settings\kweiner\Desktop\uPortalDevBooks.xsl" type="text/xsl" media="netscape"?>

<document/>

