select count(*) from UP_RAW_EVENTS where AGGREGATED=1

update UP_RAW_EVENTS set AGGREGATED=0 where AGGREGATED=1;
delete from UP_EVENT_AGGR_STATUS;
delete from UP_EVENT_SESSION_GROUPS;
delete from UP_EVENT_SESSION;
delete from UP_LOGIN_EVENT_AGGREGATE__UIDS;
delete from UP_LOGIN_EVENT_AGGREGATE;
delete from UP_CONCURRENT_USER_AGGR__SIDS;
delete from UP_CONCURRENT_USER_AGGR;
delete from UP_TAB_RENDER_AGGR;
delete from UP_PORTLET_EXEC_AGGR;

select * from UP_DATE_DIMENSION where DATE_ID=1219;
select * from UP_TIME_DIMENSION where TIME_ID=4321;


--Login Aggregations
SELECT DD.DD_YEAR, DD.DD_MONTH, DD.DD_DAY, TD.TD_HOUR, TD.TD_MINUTE, LEA.LOGIN_COUNT, LEA.UNIQUE_LOGIN_COUNT, LEA.DURATION, LEA.AGGREGATED_GROUP_ID
FROM UP_LOGIN_EVENT_AGGREGATE LEA
	LEFT JOIN UP_DATE_DIMENSION DD on LEA.DATE_DIMENSION_ID = DD.DATE_ID
	LEFT JOIN UP_TIME_DIMENSION TD on LEA.TIME_DIMENSION_ID = TD.TIME_ID
WHERE LEA.AGGR_INTERVAL='DAY'
order by DD.DD_DATE, TD.TD_TIME, LEA.AGGREGATED_GROUP_ID;


--Concurrent user aggregations
SELECT DD.DD_YEAR, DD.DD_MONTH, DD.DD_DAY, TD.TD_HOUR, TD.TD_MINUTE, CUA.CONCURRENT_USERS, CUA.DURATION, CUA.AGGREGATED_GROUP_ID
FROM UP_CONCURRENT_USER_AGGR CUA
	LEFT JOIN UP_DATE_DIMENSION DD on CUA.DATE_DIMENSION_ID = DD.DATE_ID
	LEFT JOIN UP_TIME_DIMENSION TD on CUA.TIME_DIMENSION_ID = TD.TIME_ID
WHERE CUA.AGGR_INTERVAL='FIVE_MINUTE' AND CUA.AGGREGATED_GROUP_ID=1031
order by DD.DD_DATE, TD.TD_TIME, CUA.AGGREGATED_GROUP_ID;


--Tab Render aggregations
SELECT DD.DD_YEAR, DD.DD_MONTH, DD.DD_DAY, TD.TD_HOUR, TD.TD_MINUTE, TRA.TAB_NAME, TRA.TIME_COUNT, TRA.GEOMETRIC_MEAN_TIME,
		TRA.MAX_TIME, TRA.MEAN_TIME, TRA.MIN_TIME, TRA.POPULATION_VARIANCE_TIME, TRA.SECOND_MOMENT_TIME, TRA.STD_DEVIATION_TIME,
		TRA.SUM_TIME, TRA.SUM_OF_LOGS_TIME, TRA.VARIANCE_TIME
FROM UP_TAB_RENDER_AGGR TRA
	LEFT JOIN UP_DATE_DIMENSION DD on TRA.DATE_DIMENSION_ID = DD.DATE_ID
	LEFT JOIN UP_TIME_DIMENSION TD on TRA.TIME_DIMENSION_ID = TD.TIME_ID
WHERE TRA.AGGR_INTERVAL='HOUR' AND TRA.AGGREGATED_GROUP_ID=1031
order by DD.DD_DATE, TD.TD_TIME, TRA.AGGREGATED_GROUP_ID;


--Portlet Exec aggregations
SELECT DD.DD_YEAR, DD.DD_MONTH, DD.DD_DAY, TD.TD_HOUR, TD.TD_MINUTE, PEA.FNAME, PEA.EXECUTION_TYPE, PEA.TIME_COUNT, PEA.GEOMETRIC_MEAN_TIME,
		PEA.MAX_TIME, PEA.MEAN_TIME, PEA.MIN_TIME, PEA.POPULATION_VARIANCE_TIME, PEA.SECOND_MOMENT_TIME, PEA.STD_DEVIATION_TIME,
		PEA.SUM_TIME, PEA.SUM_OF_LOGS_TIME, PEA.VARIANCE_TIME
FROM UP_PORTLET_EXEC_AGGR PEA
	LEFT JOIN UP_DATE_DIMENSION DD on PEA.DATE_DIMENSION_ID = DD.DATE_ID
	LEFT JOIN UP_TIME_DIMENSION TD on PEA.TIME_DIMENSION_ID = TD.TIME_ID
WHERE PEA.AGGR_INTERVAL='HOUR' AND PEA.AGGREGATED_GROUP_ID=1031
order by DD.DD_DATE, TD.TD_TIME, PEA.AGGREGATED_GROUP_ID;

select TAB_NAME, count(*)
from UP_TAB_RENDER_AGGR
group by TAB_NAME



select distinct USER_NAME
from UP_RAW_EVENTS
