<?xml version="1.0"?>

<?xml-stylesheet href="CGenericXSLT/footer/footer_webbrowser.xsl"  type="text/xsl" media="explorer"?>
<?xml-stylesheet href="CGenericXSLT/footer/footer_webbrowser.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet href="CGenericXSLT/footer/footer_webbrowser.xsl"  type="text/xsl" media="opera"?>
<?xml-stylesheet href="CGenericXSLT/footer/footer_wml.xsl"  type="text/xsl" media="up"?>

<document>
</document>
