<?xml version="1.0"?>

<?xml-stylesheet title="login" href="webpages/stylesheets/org/jasig/portal/tools/ChannelServlet/frame_html.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="login" href="webpages/stylesheets/org/jasig/portal/tools/ChannelServlet/frame_html.xsl" type="text/xsl" media="explorer"?>
<?xml-stylesheet title="login" href="webpages/stylesheets/org/jasig/portal/tools/ChannelServlet/frame_wml.xsl" type="text/xsl" media="up"?>

<document>
</document>
