<?xml version="1.0"?>

<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CpageViewer/CpageViewer.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CpageViewer/CpageViewer.xsl"  type="text/xsl" media="explorer"?>

<?xml-stylesheet title="turn" href="webpages/stylesheets/org/jasig/portal/channels/CpageViewer/CpageViewer.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet title="turn" href="webpages/stylesheets/org/jasig/portal/channels/CpageViewer/CpageViewer.xsl"  type="text/xsl" media="explorer"?>

<document>
</document>
