blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask a question
    url: https://groups.google.com/a/apereo.org/forum/#!forum/uportal-user
    about: Ask questions and discuss with other community members
