<?xml version="1.0"?>
<!--

    Copyright (c) 2000-2009, Jasig, Inc.
    See license distributed with this file and available online at
    https://www.ja-sig.org/svn/jasig-parent/tags/rel-10/license-header.txt

-->

<?xml-stylesheet title="default" href="/org/jasig/portal/channels/DLMUserPreferences/tab-column/default.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="newChannel" href="/org/jasig/portal/channels/DLMUserPreferences/tab-column/newChannel.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="skinList" href="/org/jasig/portal/channels/DLMUserPreferences/tab-column/skinList.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="parameters" href="/org/jasig/portal/channels/DLMUserPreferences/tab-column/parameters.xsl" type="text/xsl" media="netscape"?>


<document/>
