<?xml version="1.0"?>

<?xml-stylesheet title="browse" href="webpages/stylesheets/org/jasig/portal/channels/CLayoutManager/browse_full.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="moveTo" href="webpages/stylesheets/org/jasig/portal/channels/CLayoutManager/moveTo_full.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="editItem" href="webpages/stylesheets/org/jasig/portal/channels/CLayoutManager/editElement_full.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="firstScreen" href="webpages/stylesheets/org/jasig/portal/channels/CLayoutManager/firstScreen_full.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="editGPrefs" href="webpages/stylesheets/org/jasig/portal/channels/CLayoutManager/editGPref_full.xsl" type="text/xsl" media="netscape"?>

<document>
</document>
