package org.jasig.portal.services.persondir.support.legacy;

import junit.framework.Test;
import junit.framework.TestSuite;

/**
 * Autogenerated test suite for this package.
 * @author andrew.petro@yale.edu
 * @version $Revision$ $Date$
 */
public class AllTests {

    public static Test suite() {
        TestSuite suite = new TestSuite(
                "Test for org.jasig.portal.services.persondir.support.legacy");
        //$JUnit-BEGIN$
        suite.addTestSuite(PersonDirInfoTest.class);
        suite.addTestSuite(PersonDirXmlParserTest.class);
        //$JUnit-END$
        return suite;
    }
}