<?xml version="1.0"?>
<!--

    Copyright (c) 2000-2009, Jasig, Inc.
    See license distributed with this file and available online at
    https://www.ja-sig.org/svn/jasig-parent/tags/rel-10/license-header.txt

-->

<?xml-stylesheet title="main" href="main_html.xsl" type="text/xsl" media="explorer"?>
<?xml-stylesheet title="tree" href="tree_html.xsl" type="text/xsl" media="explorer"?>
<?xml-stylesheet title="edit" href="edit_html.xsl" type="text/xsl" media="explorer"?>

<document>
</document>
