<?xml version="1.0"?>

<?xml-stylesheet title="simpleLayout" href="sitemap.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="simpleLayout" href="sitemap.xsl" type="text/xsl" media="explorer" alternate="true"?>
<?xml-stylesheet title="simpleLayout" href="sitemap.xsl" type="text/xsl" media="opera" alternate="true"?>

<?xml-stylesheet title="aggregatedLayout" href="sitemap-al.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="aggregatedLayout" href="sitemap-al.xsl" type="text/xsl" media="explorer" alternate="true"?>
<?xml-stylesheet title="aggregatedLayout" href="sitemap-al.xsl" type="text/xsl" media="opera" alternate="true"?>

<document/>
