<?xml version="1.0"?>

<?xml-stylesheet title="view_mode" href="webpages/stylesheets/org/jasig/portal/channels/CBookmarks/view_mode_html.xsl" type="text/xsl" media="explorer"?>

<?xml-stylesheet title="edit_mode" href="webpages/stylesheets/org/jasig/portal/channels/CBookmarks/edit_mode_html.xsl" type="text/xsl" media="explorer"?>

<?xml-stylesheet title="edit_node"   href="webpages/stylesheets/org/jasig/portal/channels/CBookmarks/edit_node_html.xsl"   type="text/xsl" media="explorer"?>
<?xml-stylesheet title="add_node"    href="webpages/stylesheets/org/jasig/portal/channels/CBookmarks/add_node_html.xsl"    type="text/xsl" media="explorer"?>
<?xml-stylesheet title="move_node"   href="webpages/stylesheets/org/jasig/portal/channels/CBookmarks/move_node_html.xsl"   type="text/xsl" media="explorer"?>
<?xml-stylesheet title="delete_node" href="webpages/stylesheets/org/jasig/portal/channels/CBookmarks/delete_node_html.xsl" type="text/xsl" media="explorer"?>

<document>
</document>
