<?xml version="1.0"?>

<?xml-stylesheet title="IFrameSupport" href="webpages/stylesheets/org/jasig/portal/channels/CInlineFrame/Iframe.xsl" type="text/xsl" media="explorer"?>
<?xml-stylesheet title="IFrameSupport" href="webpages/stylesheets/org/jasig/portal/channels/CInlineFrame/Iframe.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet title="noIFrameSupport" href="webpages/stylesheets/org/jasig/portal/channels/CInlineFrame/noIframe.xsl" type="text/xsl" media="explorer"?>
<?xml-stylesheet title="noIFrameSupport" href="webpages/stylesheets/org/jasig/portal/channels/CInlineFrame/noIframe.xsl" type="text/xsl" media="netscape"?>

<document>
</document>
