<%--

    Licensed to Jasig under one or more contributor license
    agreements. See the NOTICE file distributed with this work
    for additional information regarding copyright ownership.
    Jasig licenses this file to you under the Apache License,
    Version 2.0 (the "License"); you may not use this file
    except in compliance with the License. You may obtain a
    copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on
    an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the
    specific language governing permissions and limitations
    under the License.

--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %><%-- 

This JSP provides default rendering for labels embedded within the hierarchical 
tree generated by the org/jasig/portal/channels/jsp/tree/renderer.jsp. Its 
default labeling for aspects, nodes, and actions is to return the value of
treeModel.labelData as a String as-is for embedding as the label for that
object.

The model passed to all plugged-in label rendering JSPs from
org/jasig/portal/channels/jsp/tree/renderer.jsp is:

--- requestScope.baseActionUrl
a String representing a URL for directing user responses back to the channel
containing the tree.

--- requestScope.treeModel
an instance of org.jasig.portal.channels.jsp.tree.Model. See that class for a 
description of all attributes available for use in label renderer JSPs.

--%><c:out value="${requestScope.treeModel.labelData}"/>