<?xml version="1.0"?>
<!-- CHelloWorld.ssl, part of the HelloWorld example channel -->

<?xml-stylesheet
    href="normal_netscape.xsl"
    title="normal"
    type="text/xsl"
    media="netscape"?>

<?xml-stylesheet
    href="normal_explorer.xsl"
    title="normal"
    type="text/xsl"
    media="explorer"?>

<?xml-stylesheet
    href="about.xsl"
    title="about"
    type="text/xsl"
    default="true"?>

<document>
</document>
