<?xml version="1.0"?>

<?xml-stylesheet title="view" href="/home/bw/ibs/xmlportal/webpages/stylesheets/BookmarksChannel/view_regular.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet title="edit" href="/home/bw/ibs/xmlportal/webpages/stylesheets/BookmarksChannel/edit_regular.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet title="editbookmark" href="/home/bw/ibs/xmlportal/webpages/stylesheets/BookmarksChannel/editBookmark_regular.xsl"  type="text/xsl" media="netscape"?>

<document>
</document>
