<?xml version="1.0"?>

<?xml-stylesheet title="view" href="http://localhost:8080/portal/stylesheets/BookmarksChannel/view_regular.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet alternate="true" title="view" href="http://localhost:8080/portal/stylesheets/BookmarksChannel/view_wml.xsl"  type="text/xsl" media="WAP"?>



<?xml-stylesheet title="edit" href="http://localhost:8080/portal/stylesheets/BookmarksChannel/edit_regular.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet alternate="true" title="edit" href="http://localhost:8080/portal/stylesheets/BookmarksChannel/edit_wml.xsl"  type="text/xsl" media="WAP"?>
<?xml-stylesheet alternate="true" title="edit" href="http://localhost:8080/portal/stylesheets/BookmarksChannel/edit_pp.xsl"  type="text/xsl" media="avantgo"?>



<?xml-stylesheet title="editbookmark" href="http://localhost:8080/portal/stylesheets/BookmarksChannel/editBookmark_regular.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet title="editbookmark" href="http://localhost:8080/portal/stylesheets/BookmarksChannel/editBookmark_wml.xsl"  type="text/xsl" media="WAP"?>

<document>
</document>
