<?xml version="1.0"?>

<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CGenericXSLT/RSS-0_91/rss2html_full.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CGenericXSLT/RSS-0_91/rss2html_full.xsl"  type="text/xsl" media="explorer"?>
<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CGenericXSLT/RSS-0_91/rss2html_compact.xsl"  type="text/xsl" media="avantgo"?>
<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CGenericXSLT/RSS-0_91/rss2wml.xsl"  type="text/xsl" media="WAP"?>
<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CGenericXSLT/RSS-0_91/rss2wml.xsl"  type="text/xsl" media="up"?>

<document>

</document>
