<html>
<body>

<p>Dear $displayName$,</p>

<p>We have received your request to reset your Jasig-Sakai Conference App 
password. Please <a href="$url$">use this secure URL</a> to choose a new password.</p>

<p>Please enter the password you want for your account twice on the page that opens.</p> 

<p>If you cannot access the link above, you can paste the following address into your browser: $url$</p>

<p>Welcome to uMobile and the conference!</p>

<p>- The uMobile Team<br/>
http://www.jasig.org/umobile
</p>

</body>
</html>