sequenceDiagram
    Portlet Worker   ->>  Soffit Connector: Java Portlet appel de rendu
    Soffit Connector ->>  Soffit Distante:    HTTP GET avec JWT
    Note right of Soffit Distante: La signature JWT<br>est validée par<br>la clef publique <br>depuis les propriétés
    Soffit Distante   -->> Soffit Connector: DOM fragment text
    Soffit Connector -->> Portlet Worker:   DOM fragment text
    Note over Soffit Connector: Le texte DOM n'est <br>pas modifié par<br>le Soffit Connector
