<?xml version="1.0"?>

<?xml-stylesheet href="/home/bw/ibs/xmlportal/webpages/stylesheets/RSSDocumentChannel/rss2html_full.xsl"  type="text/xsl" media="netscape"?>
<?xml-stylesheet alternate="yes" href="/home/bw/ibs/xmlportal/webpages/stylesheets/RSSDocumentChannel/rss2html_compact.xsl"  type="text/xsl" media="explorer"?>
<?xml-stylesheet alternate="yes" href="/home/bw/ibs/xmlportal/webpages/stylesheets/RSSDocumentChannel/rss2html_compact.xsl"  type="text/xsl" media="avantgo"?>

<document>

</document>
