<?xml version="1.0"?>

<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CLogin/html.xsl" type="text/xsl" media="netscape"?>
<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CLogin/html.xsl" type="text/xsl" media="explorer"?>
<?xml-stylesheet href="webpages/stylesheets/org/jasig/portal/channels/CLogin/login_wml.xsl" type="text/xsl" media="up"?>

<document>
</document>
